server:
 servlet:
  context-path: /bcp
jwt:
 secret: javainuse
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/bcp?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  username: root
  password: mysql
  platform: mysql
 jpa:
  database-platform: org.hibernate.dialect.MySQL57Dialect
  hibernate.ddl-auto: update
 main:
  allow-bean-definition-overriding: true
 profiles:
  active: development